"""The 61 built-in factor kernels, kept in upstream's declaration order so the
two files can be read side by side.

Ported from QuantDinger (https://github.com/OpenByteInc/QuantDinger),
Copyright Open Byte Inc., licensed under the Apache License, Version 2.0
(http://www.apache.org/licenses/LICENSE-2.0). Source:
`backend_api_python/app/services/factors/registry.py` (every `_`-prefixed
kernel and guard helper between lines 280 and 1005).

Changed on port: pandas/numpy are unavailable here, so every kernel was
rewritten against `app/engine/factors/frame.py`'s stdlib stand-ins. The
translation is mechanical and the numbers are frozen against upstream's own
output in `tests/test_factors_golden.json`, which was generated by running the
upstream implementation (pandas 3.0.5) over the same synthetic bars.

Nothing was "cleaned up" in the process. Six upstream behaviours look like
defects, are load-bearing for the numbers, and are reproduced deliberately:

  * **Bar-0 true range.** `_true_range` takes a row-wise max that SKIPS NaN,
    so row 0 — whose two previous-close terms are NaN — yields `high - low`
    instead of being dropped. The TR series is therefore as long as the frame
    and one element longer than TA-Lib's. `atr`, `atr_pct`, `supertrend`,
    `vortex`, `choppiness` and `keltner_channels` all inherit that offset.
  * **Mixed `ddof`.** `bollinger_bands` uses the population deviation;
    `realized_volatility`, `volume_zscore` and `mean_reversion_zscore` use the
    sample one. They are not unified.
  * **The ADX loop.** `_adx_components` iterates from `period - 1` but only
    advances the Wilder sums `if index >= period`, so the first DX comes off
    the raw window sums; and the returned `plus_di`/`minus_di` are the last
    iteration's leaked loop locals rather than a separate final computation.
  * **The KDJ seed.** K and D start at 50.0 (the Chinese convention, not
    Wilder's), `rsv` falls back to 50.0 on a degenerate range, and the loop
    runs over the ENTIRE frame rather than a bounded window.
  * **NaN poisoning in `amihud_illiquidity`.** It drops to raw arrays before
    averaging, so one bar with zero traded value makes the whole factor NaN.
    That is the signal (the bar did not trade), not a bug to paper over.
  * **SMA-seeded EMA.** `_ema_values` seeds at index `period - 1` with the
    simple mean of the first `period` observations, then applies
    `2 / (period + 1)`. Every EMA-derived factor inherits that seed.
"""

from __future__ import annotations

import math
from collections.abc import Mapping, Sequence
from typing import Any

from app.engine.factors.frame import (
    NAN,
    FactorError,
    Frame,
    cummax,
    cumsum,
    diff,
    divide,
    dropna,
    fillna,
    log,
    mean,
    nan_filter,
    nanmax,
    nanmean,
    nanmin,
    nansum,
    pct_change,
    replace_zero_with_nan,
    rolling_max,
    rolling_mean,
    rolling_min,
    row_max,
    row_min,
    shift,
    sqrt,
    stdev,
)
from app.engine.factors.frame import (
    argmax as np_argmax,
)
from app.engine.factors.frame import (
    argmin as np_argmin,
)

# Upstream's global parameter bounds. Note that individual kernels pass a
# `minimum` of 1 where a one-bar lookback is meaningful (`smooth_k`,
# `slope_period`, `k_period`, `d_period`, KAMA's `fast_period`).
MIN_PERIOD = 2
MAX_PERIOD = 5000

TRADING_DAYS_PER_YEAR = 252.0

# ---------------------------------------------------------------------------
# Guard helpers (upstream `registry.py:280-396`)
# ---------------------------------------------------------------------------


def _period(params: Mapping[str, Any], key: str = "period", minimum: int = MIN_PERIOD) -> int:
    """Upstream's `int(params.get(key) or minimum)`.

    The `or` matters: a falsy value (0, "", None, False) falls back to the
    minimum, while a truthy non-integer string still goes through `int()` and
    fails as `factor.invalidParameter`.
    """
    try:
        value = int(params.get(key) or minimum)
    except (TypeError, ValueError) as exc:
        raise FactorError("factor.invalidParameter") from exc
    if value < minimum or value > MAX_PERIOD:
        raise FactorError("factor.invalidParameter")
    return value


def _positive_float(params: Mapping[str, Any], key: str, default: float) -> float:
    try:
        value = float(params.get(key, default))
    except (TypeError, ValueError) as exc:
        raise FactorError("factor.invalidParameter") from exc
    if not math.isfinite(value) or value <= 0:
        raise FactorError("factor.invalidParameter")
    return value


def _choice(params: Mapping[str, Any], key: str, allowed: set[str], default: str) -> str:
    value = str(params.get(key, default) or default).strip().lower()
    if value not in allowed:
        raise FactorError("factor.invalidParameter")
    return value


def _require(values: Sequence[float], count: int) -> list[float]:
    clean = nan_filter(values)
    if len(clean) < count:
        raise FactorError("factor.insufficientHistory")
    return clean


def _ema_values(values: Sequence[float], period: int) -> list[float]:
    """The system-wide EMA convention: SMA seed at index `period - 1`, then
    `2 / (period + 1)`. Every EMA-derived factor goes through here."""
    clean = nan_filter(values)
    if len(clean) < period:
        raise FactorError("factor.insufficientHistory")
    out = [NAN] * len(clean)
    out[period - 1] = sum(clean[:period]) / period
    multiplier = 2.0 / (period + 1.0)
    for index in range(period, len(clean)):
        out[index] = (clean[index] - out[index - 1]) * multiplier + out[index - 1]
    return out


def _wma_values(values: Sequence[float], period: int) -> list[float]:
    """Linearly weighted moving average — only `hma` uses it."""
    clean = _require(values, period)
    weights = [float(index) for index in range(1, period + 1)]
    weight_sum = sum(weights)
    out = [NAN] * len(clean)
    for index in range(period - 1, len(clean)):
        window = clean[index - period + 1 : index + 1]
        out[index] = sum(a * b for a, b in zip(window, weights, strict=True)) / weight_sum
    return out


def _true_range(frame: Frame) -> list[float]:
    """Wilder's true range, INCLUDING bar 0.

    Upstream stacks the three candidate ranges and takes a row-wise max that
    skips NaN, so bar 0 — where both previous-close terms are NaN — survives
    as `high - low`. Reproducing that offset is what keeps `atr` and friends
    aligned with upstream instead of with TA-Lib.
    """
    high = frame.raw("high")
    low = frame.raw("low")
    close = frame.raw("close")
    previous = shift(close, 1)
    candidates = [
        [a - b for a, b in zip(high, low, strict=True)],
        [abs(a - b) for a, b in zip(high, previous, strict=True)],
        [abs(a - b) for a, b in zip(low, previous, strict=True)],
    ]
    stacked = row_max(row_max(candidates[0], candidates[1]), candidates[2])
    return dropna(stacked)


def _wilder_last(values: Sequence[float], period: int) -> float:
    clean = _require(values, period)
    result = sum(clean[:period]) / period
    for value in clean[period:]:
        result = (result * (period - 1) + value) / period
    return result


# ---------------------------------------------------------------------------
# Shared kernels (upstream `registry.py:294-360`)
# ---------------------------------------------------------------------------


def _return(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = nan_filter(frame.raw("close"))
    if len(values) <= period:
        raise FactorError("factor.insufficientHistory")
    return divide(values[-1], values[-period - 1]) - 1.0


def _realized_vol(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    returns = dropna(pct_change(nan_filter(frame.raw("close"))))
    if len(returns) < period:
        raise FactorError("factor.insufficientHistory")
    return stdev(returns[-period:], ddof=1) * math.sqrt(TRADING_DAYS_PER_YEAR)


def _ema_slope(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    slope_period = _period(params, "slope_period", minimum=1)
    values = _require(frame.raw("close"), period + slope_period)
    ema = _ema_values(values, period)
    base = ema[-slope_period - 1]
    return divide(ema[-1], base) - 1.0 if base else NAN


def _atr_pct(frame: Frame, params: Mapping[str, Any]) -> float:
    last_close = frame.raw("close")[-1]
    return divide(_atr(frame, params), last_close) if last_close else NAN


def _zscore_last(series: Sequence[float], params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = nan_filter(series)
    if len(values) < period:
        raise FactorError("factor.insufficientHistory")
    window = values[-period:]
    deviation = stdev(window, ddof=1)
    if not deviation > 0:
        return 0.0
    return (window[-1] - sum(window) / len(window)) / deviation


def _turnover(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = nan_filter(frame.product("close", "volume"))
    if len(values) < period:
        raise FactorError("factor.insufficientHistory")
    return sum(values[-period:]) / period


def _last_value(frame: Frame, field: str) -> float:
    values = nan_filter(frame.raw(field))
    if not values:
        raise FactorError("factor.insufficientHistory")
    return values[-1]


def _ratio_last(frame: Frame, numerator: str, denominator: str) -> float:
    numerator_value = _last_value(frame, numerator)
    denominator_value = _last_value(frame, denominator)
    return divide(numerator_value, denominator_value) if denominator_value else NAN


def _growth_last(frame: Frame, field: str) -> float:
    values = nan_filter(frame.raw(field))
    if len(values) < 2:
        raise FactorError("factor.insufficientHistory")
    previous = values[-2]
    return divide(values[-1], previous) - 1.0 if previous else NAN


# ---------------------------------------------------------------------------
# Technical kernels (upstream `registry.py:399-1005`)
# ---------------------------------------------------------------------------


def _sma(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _require(frame.raw("close"), period)
    return sum(values[-period:]) / period


def _ema(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    return _ema_values(frame.raw("close"), period)[-1]


def _ma_distance(frame: Frame, params: Mapping[str, Any], *, exponential: bool) -> float:
    values = nan_filter(frame.raw("close"))
    average = _ema(frame, params) if exponential else _sma(frame, params)
    latest = values[-1]
    return divide(latest, average) - 1.0 if average else NAN


def _rsi(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _require(frame.raw("close"), period + 1)
    deltas = dropna(diff(values))
    gains = [max(delta, 0.0) for delta in deltas]
    losses = [-min(delta, 0.0) for delta in deltas]
    avg_gain = sum(gains[:period]) / period
    avg_loss = sum(losses[:period]) / period
    for index in range(period, len(deltas)):
        avg_gain = (avg_gain * (period - 1) + gains[index]) / period
        avg_loss = (avg_loss * (period - 1) + losses[index]) / period
    if avg_loss <= 0:
        return 100.0
    return 100.0 - 100.0 / (1.0 + avg_gain / avg_loss)


def _macd(frame: Frame, params: Mapping[str, Any]) -> float:
    fast = _period(params, "fast_period")
    slow = _period(params, "slow_period")
    signal = _period(params, "signal_period")
    if fast >= slow:
        raise FactorError("factor.invalidParameter")
    values = _require(frame.raw("close"), slow + signal - 1)
    fast_values = _ema_values(values, fast)
    slow_values = _ema_values(values, slow)
    line = dropna([a - b for a, b in zip(fast_values, slow_values, strict=True)])
    signal_values = _ema_values(line, signal)
    macd_value = line[-1]
    signal_value = signal_values[-1]
    output = _choice(params, "output", {"line", "signal", "histogram"}, "histogram")
    if output == "line":
        return macd_value
    if output == "signal":
        return signal_value
    return macd_value - signal_value


def _bollinger(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    multiplier = _positive_float(params, "stddev", 2.0)
    values = _require(frame.raw("close"), period)
    window = values[-period:]
    middle = sum(window) / period
    # POPULATION deviation here; the z-score factors use the sample one.
    deviation = stdev(window, ddof=0)
    upper = middle + multiplier * deviation
    lower = middle - multiplier * deviation
    output = _choice(
        params, "output", {"upper", "middle", "lower", "bandwidth", "position"}, "position"
    )
    if output == "upper":
        return upper
    if output == "middle":
        return middle
    if output == "lower":
        return lower
    if output == "bandwidth":
        return divide(upper - lower, middle) if middle else NAN
    return (values[-1] - lower) / (upper - lower) if upper > lower else 0.5


def _atr(frame: Frame, params: Mapping[str, Any]) -> float:
    return _wilder_last(_true_range(frame), _period(params))


def _stochastic(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    smooth_k = _period(params, "smooth_k", minimum=1)
    smooth_d = _period(params, "smooth_d", minimum=1)
    required = period + smooth_k + smooth_d - 2
    if frame.row_count < required:
        raise FactorError("factor.insufficientHistory")
    close = frame.raw("close")
    highest = rolling_max(frame.raw("high"), period)
    lowest = rolling_min(frame.raw("low"), period)
    spread = replace_zero_with_nan([a - b for a, b in zip(highest, lowest, strict=True)])
    raw_k = [
        divide(100.0 * (c - low), width)
        for c, low, width in zip(close, lowest, spread, strict=True)
    ]
    k = rolling_mean(raw_k, smooth_k)
    d = rolling_mean(k, smooth_d)
    output = _choice(params, "output", {"k", "d"}, "k")
    value = d[-1] if output == "d" else k[-1]
    if not math.isfinite(value):
        raise FactorError("factor.insufficientHistory")
    return value


def _kdj(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    k_period = _period(params, "k_period", minimum=1)
    d_period = _period(params, "d_period", minimum=1)
    if frame.row_count < period:
        raise FactorError("factor.insufficientHistory")
    high = frame.raw("high")
    low = frame.raw("low")
    close = frame.raw("close")
    # The Chinese convention: K and D are seeded at 50, not at the first RSV,
    # and the recursion runs over the whole frame rather than a window.
    k_value = 50.0
    d_value = 50.0
    for index in range(period - 1, frame.row_count):
        highest = nanmax(high[index - period + 1 : index + 1])
        lowest = nanmin(low[index - period + 1 : index + 1])
        if highest <= lowest:
            rsv = 50.0
        else:
            rsv = (close[index] - lowest) / (highest - lowest) * 100.0
        k_value = ((k_period - 1) * k_value + rsv) / k_period
        d_value = ((d_period - 1) * d_value + k_value) / d_period
    output = _choice(params, "output", {"k", "d", "j"}, "j")
    return {"k": k_value, "d": d_value, "j": 3.0 * k_value - 2.0 * d_value}[output]


def _typical_price(frame: Frame) -> list[float]:
    high = frame.raw("high")
    low = frame.raw("low")
    close = frame.raw("close")
    return [(h + low_value + c) / 3.0 for h, low_value, c in zip(high, low, close, strict=True)]


def _cci(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _require(_typical_price(frame), period)[-period:]
    average = sum(values) / period
    deviation = sum(abs(value - average) for value in values) / period
    return (values[-1] - average) / (0.015 * deviation) if deviation > 0 else 0.0


def _williams_r(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    if frame.row_count < period:
        raise FactorError("factor.insufficientHistory")
    high = nanmax(frame.raw("high")[-period:])
    low = nanmin(frame.raw("low")[-period:])
    close = frame.raw("close")[-1]
    return -50.0 if high <= low else -100.0 * (high - close) / (high - low)


def _mfi(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    if frame.row_count < period + 1:
        raise FactorError("factor.insufficientHistory")
    typical = _typical_price(frame)
    volume = fillna(frame.raw("volume"), 0.0)
    flow = [a * b for a, b in zip(typical, volume, strict=True)]
    direction = diff(typical)
    positive = nansum(
        [value if step > 0 else 0.0 for value, step in zip(flow, direction, strict=True)][-period:]
    )
    negative = nansum(
        [value if step < 0 else 0.0 for value, step in zip(flow, direction, strict=True)][-period:]
    )
    if negative <= 0:
        return 100.0
    return 100.0 - 100.0 / (1.0 + divide(positive, negative))


def _adx_components(frame: Frame, period: int) -> tuple[float, float, float]:
    if frame.row_count < period + 1:
        raise FactorError("factor.insufficientHistory")
    high = frame.raw("high")
    low = frame.raw("low")
    close = frame.raw("close")
    tr: list[float] = []
    plus_dm: list[float] = []
    minus_dm: list[float] = []
    for index in range(1, frame.row_count):
        tr.append(
            max(
                high[index] - low[index],
                abs(high[index] - close[index - 1]),
                abs(low[index] - close[index - 1]),
            )
        )
        up = high[index] - high[index - 1]
        down = low[index - 1] - low[index]
        plus_dm.append(up if up > down and up > 0 else 0.0)
        minus_dm.append(down if down > up and down > 0 else 0.0)
    if len(tr) < period:
        raise FactorError("factor.insufficientHistory")
    smooth_tr = sum(tr[:period])
    smooth_plus = sum(plus_dm[:period])
    smooth_minus = sum(minus_dm[:period])
    # The loop starts one step before the smoothing does, so the first DX is
    # taken off the raw window sums; and `plus_di`/`minus_di` below are the
    # last iteration's values, exactly as upstream's leaked loop scope yields.
    plus_di = 0.0
    minus_di = 0.0
    dx_values: list[float] = []
    for index in range(period - 1, len(tr)):
        if index >= period:
            smooth_tr = smooth_tr - smooth_tr / period + tr[index]
            smooth_plus = smooth_plus - smooth_plus / period + plus_dm[index]
            smooth_minus = smooth_minus - smooth_minus / period + minus_dm[index]
        plus_di = 100.0 * smooth_plus / smooth_tr if smooth_tr else 0.0
        minus_di = 100.0 * smooth_minus / smooth_tr if smooth_tr else 0.0
        total = plus_di + minus_di
        dx_values.append(100.0 * abs(plus_di - minus_di) / total if total else 0.0)
    adx_value = dx_values[0]
    for value in dx_values[1:]:
        adx_value = (adx_value * (period - 1) + value) / period
    return adx_value, plus_di, minus_di


def _adx(frame: Frame, params: Mapping[str, Any]) -> float:
    values = _adx_components(frame, _period(params))
    output = _choice(params, "output", {"adx", "plus_di", "minus_di"}, "adx")
    return values[{"adx": 0, "plus_di": 1, "minus_di": 2}[output]]


def _aroon(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    if frame.row_count < period:
        raise FactorError("factor.insufficientHistory")
    high = frame.raw("high")[-period:]
    low = frame.raw("low")[-period:]
    up = 100.0 * (np_argmax(high) + 1) / period
    down = 100.0 * (np_argmin(low) + 1) / period
    output = _choice(params, "output", {"up", "down", "oscillator"}, "oscillator")
    return {"up": up, "down": down, "oscillator": up - down}[output]


def _trix(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _require(frame.raw("close"), period * 3 + 1)
    first = dropna(_ema_values(values, period))
    second = dropna(_ema_values(first, period))
    third = dropna(_ema_values(second, period))
    if len(third) < 2 or third[-2] == 0:
        raise FactorError("factor.insufficientHistory")
    return divide(third[-1], third[-2]) - 1.0


def _supertrend(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    multiplier = _positive_float(params, "multiplier", 3.0)
    if frame.row_count < period + 1:
        raise FactorError("factor.insufficientHistory")
    high = frame.raw("high")
    low = frame.raw("low")
    close = frame.raw("close")
    tr = _true_range(frame)
    atr_values = [NAN] * frame.row_count
    atr_values[period - 1] = nanmean(tr[:period])
    for index in range(period, frame.row_count):
        atr_values[index] = (atr_values[index - 1] * (period - 1) + tr[index]) / period
    direction = 1
    final_upper = final_lower = NAN
    line = NAN
    for index in range(period - 1, frame.row_count):
        midpoint = (high[index] + low[index]) / 2.0
        basic_upper = midpoint + multiplier * atr_values[index]
        basic_lower = midpoint - multiplier * atr_values[index]
        if index == period - 1:
            final_upper, final_lower = basic_upper, basic_lower
        else:
            if basic_upper < final_upper or close[index - 1] > final_upper:
                final_upper = basic_upper
            if basic_lower > final_lower or close[index - 1] < final_lower:
                final_lower = basic_lower
            if direction < 0 and close[index] > final_upper:
                direction = 1
            elif direction > 0 and close[index] < final_lower:
                direction = -1
        line = final_lower if direction > 0 else final_upper
    output = _choice(params, "output", {"direction", "line"}, "direction")
    return float(direction) if output == "direction" else line


def _downside_volatility(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    returns = dropna(pct_change(_require(frame.raw("close"), period + 1)))[-period:]
    downside = [value if value < 0 else 0.0 for value in returns]
    return sqrt(nanmean([value * value for value in downside])) * math.sqrt(
        TRADING_DAYS_PER_YEAR
    )


def _max_drawdown(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _require(frame.raw("close"), period)[-period:]
    drawdown = [
        divide(value, peak) - 1.0 for value, peak in zip(values, cummax(values), strict=True)
    ]
    return nanmin(drawdown)


def _donchian(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    if frame.row_count < period:
        raise FactorError("factor.insufficientHistory")
    upper = nanmax(frame.raw("high")[-period:])
    lower = nanmin(frame.raw("low")[-period:])
    middle = (upper + lower) / 2.0
    output = _choice(params, "output", {"upper", "middle", "lower", "position"}, "position")
    if output == "upper":
        return upper
    if output == "middle":
        return middle
    if output == "lower":
        return lower
    close = frame.raw("close")[-1]
    return (close - lower) / (upper - lower) if upper > lower else 0.5


def _keltner(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    atr_period = _period(params, "atr_period")
    multiplier = _positive_float(params, "multiplier", 2.0)
    middle = _ema(frame, {"period": period})
    atr_value = _atr(frame, {"period": atr_period})
    upper = middle + multiplier * atr_value
    lower = middle - multiplier * atr_value
    output = _choice(params, "output", {"upper", "middle", "lower", "position"}, "position")
    if output == "upper":
        return upper
    if output == "middle":
        return middle
    if output == "lower":
        return lower
    close = frame.raw("close")[-1]
    return (close - lower) / (upper - lower) if upper > lower else 0.5


def _volume_ratio(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _require(frame.raw("volume"), period)
    average = sum(values[-period:]) / period
    return divide(values[-1], average) if average else NAN


def _normalized_slope(
    values: Sequence[float], volumes: Sequence[float], period: int
) -> float:
    if len(values) <= period:
        raise FactorError("factor.insufficientHistory")
    denominator = sum(abs(value) for value in nan_filter(volumes)[-period:])
    return divide(values[-1] - values[-period - 1], denominator) if denominator else 0.0


def _obv_series(frame: Frame) -> list[float]:
    close = frame.raw("close")
    volume = fillna(frame.raw("volume"), 0.0)
    direction = [
        0.0 if step == 0 or math.isnan(step) else math.copysign(1.0, step)
        for step in fillna(diff(close), 0.0)
    ]
    return cumsum([a * b for a, b in zip(direction, volume, strict=True)])


def _obv(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _obv_series(frame)
    output = _choice(params, "output", {"value", "slope"}, "slope")
    if output == "value":
        return values[-1]
    return _normalized_slope(values, frame.raw("volume"), period)


def _ad_series(frame: Frame) -> list[float]:
    high = frame.raw("high")
    low = frame.raw("low")
    close = frame.raw("close")
    volume = fillna(frame.raw("volume"), 0.0)
    spread = replace_zero_with_nan([h - low_value for h, low_value in zip(high, low, strict=True)])
    multiplier = [
        divide((c - low_value) - (h - c), width)
        for h, low_value, c, width in zip(high, low, close, spread, strict=True)
    ]
    return cumsum(
        [a * b for a, b in zip(fillna(multiplier, 0.0), volume, strict=True)]
    )


def _ad_line(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _ad_series(frame)
    output = _choice(params, "output", {"value", "slope"}, "slope")
    if output == "value":
        return values[-1]
    return _normalized_slope(values, frame.raw("volume"), period)


def _chaikin(frame: Frame, params: Mapping[str, Any]) -> float:
    fast = _period(params, "fast_period")
    slow = _period(params, "slow_period")
    if fast >= slow:
        raise FactorError("factor.invalidParameter")
    values = _ad_series(frame)
    fast_value = _ema_values(values, fast)[-1]
    slow_value = _ema_values(values, slow)[-1]
    scale = nanmean(nan_filter(frame.raw("volume"))[-slow:])
    return divide(fast_value - slow_value, scale) if scale else 0.0


def _vwap(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    if frame.row_count < period:
        raise FactorError("factor.insufficientHistory")
    typical = _typical_price(frame)
    volume = fillna(frame.raw("volume"), 0.0)
    denominator = nansum(volume[-period:])
    if denominator <= 0:
        return NAN
    weighted = [a * b for a, b in zip(typical[-period:], volume[-period:], strict=True)]
    value = nansum(weighted) / denominator
    output = _choice(params, "output", {"value", "distance"}, "distance")
    close = frame.raw("close")[-1]
    return value if output == "value" else divide(close, value) - 1.0


def _cmf(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    if frame.row_count < period:
        raise FactorError("factor.insufficientHistory")
    high = frame.raw("high")
    low = frame.raw("low")
    close = frame.raw("close")
    volume = fillna(frame.raw("volume"), 0.0)
    spread = replace_zero_with_nan([h - low_value for h, low_value in zip(high, low, strict=True)])
    multiplier = fillna(
        [
            divide((c - low_value) - (h - c), width)
            for h, low_value, c, width in zip(high, low, close, spread, strict=True)
        ],
        0.0,
    )
    money_flow_volume = [a * b for a, b in zip(multiplier, volume, strict=True)]
    denominator = nansum(volume[-period:])
    return divide(nansum(money_flow_volume[-period:]), denominator) if denominator else 0.0


def _dema(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    first = dropna(_ema_values(frame.raw("close"), period))
    second = dropna(_ema_values(first, period))
    return 2.0 * first[-1] - second[-1]


def _tema(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    first = dropna(_ema_values(frame.raw("close"), period))
    second = dropna(_ema_values(first, period))
    third = dropna(_ema_values(second, period))
    return 3.0 * first[-1] - 3.0 * second[-1] + third[-1]


def _zlema(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    lag = max(1, (period - 1) // 2)
    close = _require(frame.raw("close"), period + lag)
    lagged = shift(close, lag)
    adjusted = dropna(
        [value + (value - previous) for value, previous in zip(close, lagged, strict=True)]
    )
    return _ema_values(adjusted, period)[-1]


def _hma(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    half_period = max(1, period // 2)
    root_period = max(1, int(math.sqrt(period)))
    values = _require(frame.raw("close"), period + root_period)
    half = _wma_values(values, half_period)
    full = _wma_values(values, period)
    raw = dropna([2.0 * a - b for a, b in zip(half, full, strict=True)])
    return _wma_values(raw, root_period)[-1]


def _kama(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    fast = _period(params, "fast_period", minimum=1)
    slow = _period(params, "slow_period")
    if fast >= slow:
        raise FactorError("factor.invalidParameter")
    values = _require(frame.raw("close"), period + 1)
    kama = sum(values[:period]) / period
    fast_constant = 2.0 / (fast + 1.0)
    slow_constant = 2.0 / (slow + 1.0)
    for index in range(period, len(values)):
        change = abs(values[index] - values[index - period])
        volatility = nansum([abs(step) for step in diff(values[index - period : index + 1])])
        efficiency = change / volatility if volatility else 0.0
        smoothing = (efficiency * (fast_constant - slow_constant) + slow_constant) ** 2
        kama += smoothing * (values[index] - kama)
    return kama


def _ppo(frame: Frame, params: Mapping[str, Any]) -> float:
    fast = _period(params, "fast_period")
    slow = _period(params, "slow_period")
    if fast >= slow:
        raise FactorError("factor.invalidParameter")
    fast_value = _ema_values(frame.raw("close"), fast)[-1]
    slow_value = _ema_values(frame.raw("close"), slow)[-1]
    # Upstream spells this `100.0 * (fast - slow) / slow`; the multiply comes
    # first, and reassociating it would move the last bit of the result.
    return divide(100.0 * (fast_value - slow_value), slow_value) if slow_value else NAN


def _cmo(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    changes = dropna(diff(_require(frame.raw("close"), period + 1)))[-period:]
    gains = sum(max(change, 0.0) for change in changes)
    losses = sum(-min(change, 0.0) for change in changes)
    total = gains + losses
    return 100.0 * (gains - losses) / total if total else 0.0


def _awesome_oscillator(frame: Frame, params: Mapping[str, Any]) -> float:
    fast = _period(params, "fast_period")
    slow = _period(params, "slow_period")
    if fast >= slow:
        raise FactorError("factor.invalidParameter")
    high = frame.raw("high")
    low = frame.raw("low")
    median = [(h + low_value) / 2.0 for h, low_value in zip(high, low, strict=True)]
    values = _require(median, slow)
    return sum(values[-fast:]) / fast - sum(values[-slow:]) / slow


def _ultimate_oscillator(frame: Frame, params: Mapping[str, Any]) -> float:
    fast = _period(params, "fast_period")
    medium = _period(params, "medium_period")
    slow = _period(params, "slow_period")
    if not fast < medium < slow:
        raise FactorError("factor.invalidParameter")
    if frame.row_count < slow + 1:
        raise FactorError("factor.insufficientHistory")
    high = frame.raw("high")
    low = frame.raw("low")
    close = frame.raw("close")
    previous = shift(close, 1)
    lowest = row_min(low, previous)
    buying_pressure = [c - value for c, value in zip(close, lowest, strict=True)]
    true_range = [
        top - bottom
        for top, bottom in zip(row_max(high, previous), lowest, strict=True)
    ]

    def average(length: int) -> float:
        denominator = nansum(true_range[-length:])
        return divide(nansum(buying_pressure[-length:]), denominator) if denominator else 0.0

    return 100.0 * (4.0 * average(fast) + 2.0 * average(medium) + average(slow)) / 7.0


def _tsi(frame: Frame, params: Mapping[str, Any]) -> float:
    slow = _period(params, "slow_period")
    fast = _period(params, "fast_period")
    momentum = dropna(diff(_require(frame.raw("close"), slow + fast + 1)))
    absolute = [abs(value) for value in momentum]
    numerator = dropna(_ema_values(dropna(_ema_values(momentum, slow)), fast))
    denominator = dropna(_ema_values(dropna(_ema_values(absolute, slow)), fast))
    scale = denominator[-1]
    return divide(100.0 * numerator[-1], scale) if scale else 0.0


def _vortex(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    if frame.row_count < period + 1:
        raise FactorError("factor.insufficientHistory")
    high = frame.raw("high")
    low = frame.raw("low")
    true_range = _true_range(frame)[-period:]
    denominator = nansum(true_range)
    if denominator <= 0:
        return 0.0
    upward = [abs(h - previous) for h, previous in zip(high, shift(low, 1), strict=True)]
    downward = [
        abs(low_value - previous) for low_value, previous in zip(low, shift(high, 1), strict=True)
    ]
    plus = nansum(upward[-period:]) / denominator
    minus = nansum(downward[-period:]) / denominator
    output = _choice(params, "output", {"plus", "minus", "oscillator"}, "oscillator")
    return {"plus": plus, "minus": minus, "oscillator": plus - minus}[output]


def _choppiness(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    if frame.row_count < period + 1:
        raise FactorError("factor.insufficientHistory")
    high = frame.raw("high")[-period:]
    low = frame.raw("low")[-period:]
    price_range = nanmax(high) - nanmin(low)
    if price_range <= 0:
        return 100.0
    total = nansum(_true_range(frame)[-period:])
    return 100.0 * math.log10(total / price_range) / math.log10(period)


def _efficiency_ratio(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _require(frame.raw("close"), period + 1)
    change = abs(values[-1] - values[-period - 1])
    volatility = nansum([abs(step) for step in diff(values[-period - 1 :])])
    return change / volatility if volatility else 0.0


def _elder_ray(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    average = _ema_values(frame.raw("close"), period)[-1]
    output = _choice(params, "output", {"bull", "bear"}, "bull")
    field = "high" if output == "bull" else "low"
    return frame.raw(field)[-1] - average


def _force_index(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    close = frame.raw("close")
    volume = frame.raw("volume")
    raw = dropna([step * value for step, value in zip(diff(close), volume, strict=True)])
    return _ema_values(raw, period)[-1]


def _ulcer_index(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    values = _require(frame.raw("close"), period)[-period:]
    drawdown = [
        100.0 * (divide(value, peak) - 1.0)
        for value, peak in zip(values, cummax(values), strict=True)
    ]
    return sqrt(nanmean([value * value for value in drawdown]))


def _parkinson_volatility(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    high = _require(frame.raw("high"), period)[-period:]
    low = replace_zero_with_nan(_require(frame.raw("low"), period)[-period:])
    ratios = [log(divide(h, low_value)) for h, low_value in zip(high, low, strict=True)]
    variance = nanmean([value * value for value in ratios]) / (4.0 * math.log(2.0))
    return math.sqrt(max(0.0, variance) * TRADING_DAYS_PER_YEAR)


def _garman_klass_volatility(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    high = _require(frame.raw("high"), period)[-period:]
    low = replace_zero_with_nan(_require(frame.raw("low"), period)[-period:])
    open_values = replace_zero_with_nan(_require(frame.raw("open"), period)[-period:])
    close = _require(frame.raw("close"), period)[-period:]
    coefficient = 2.0 * math.log(2.0) - 1.0
    variance = [
        0.5 * log(divide(h, low_value)) ** 2 - coefficient * log(divide(c, o)) ** 2
        for h, low_value, c, o in zip(high, low, close, open_values, strict=True)
    ]
    return math.sqrt(max(0.0, nanmean(variance)) * TRADING_DAYS_PER_YEAR)


def _amihud_illiquidity(frame: Frame, params: Mapping[str, Any]) -> float:
    period = _period(params)
    close = _require(frame.raw("close"), period + 1)
    volume = frame.raw("volume")[-period:]
    returns = [abs(value) for value in pct_change(close)][-period:]
    traded_value = replace_zero_with_nan(
        [c * v for c, v in zip(close[-period:], volume, strict=True)]
    )
    # `mean`, not `nanmean`: upstream drops to raw arrays here, so a single
    # untraded bar makes the whole factor NaN. That is the answer, not a gap.
    return mean([divide(r, t) for r, t in zip(returns, traded_value, strict=True)])
