from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol

from app.models.jobs import ArtifactReference, JobCreateRequest, JobRecord, JobStatus, ProgressEvent


class JobStore(Protocol):
    async def initialize(self) -> None: ...

    async def create_or_get(
        self, request: JobCreateRequest, timeout_seconds: int, max_attempts: int
    ) -> tuple[JobRecord, bool]: ...

    async def get_for_user(self, job_id: str, user_id: int) -> JobRecord | None: ...
    async def get_internal(self, job_id: str) -> JobRecord | None: ...
    async def delete(self, job_id: str) -> None: ...
    async def transition(self, job_id: str, status: JobStatus, **updates: Any) -> JobRecord: ...
    async def request_cancel(self, job_id: str, user_id: int) -> JobRecord | None: ...
    async def append_progress(
        self,
        job_id: str,
        percent: int,
        stage: str,
        message: str,
        metadata: Mapping[str, Any] | None = None,
    ) -> ProgressEvent: ...

    async def events_for_user(self, job_id: str, user_id: int) -> list[ProgressEvent] | None: ...
    async def attach_artifact(self, job_id: str, artifact: ArtifactReference) -> None: ...
    async def get_artifact_for_user(
        self, artifact_id: str, job_id: str, user_id: int
    ) -> ArtifactReference | None: ...
    async def recover_pending(self) -> list[str]: ...
    async def available(self) -> bool: ...
