import requests

BASE_URL = "http://localhost:3000"
LOGIN_ENDPOINT = "/api/auth/login"
SIGNALS_GENERATE_ENDPOINT = "/api/signals/generate"
ME_ENDPOINT = "/api/me"
SIGNALS_NEW_ENDPOINT = "/signals/new"

ADMIN_EMAIL = "admin@aichart.local"
ADMIN_PASSWORD = "admin12345"

TIMEOUT = 30

def test_postapisignalsgeneratewithvalidinputsandquota():
    session = requests.Session()

    # 1. Login as admin to get JWT token cookie for authenticated requests
    login_payload = {"email": ADMIN_EMAIL, "password": ADMIN_PASSWORD}
    login_resp = session.post(BASE_URL + LOGIN_ENDPOINT, json=login_payload, timeout=TIMEOUT)
    assert login_resp.status_code == 200, f"Login failed: {login_resp.text}"
    # It sets cookies (JWT) for session auth usage

    # 2. Check user profile and quota to ensure sufficient credits
    me_resp = session.get(BASE_URL + ME_ENDPOINT, timeout=TIMEOUT)
    assert me_resp.status_code == 200, f"Failed to get user profile: {me_resp.text}"
    me_data = me_resp.json()
    remaining_credits = None
    if "quota" in me_data:
        # quota may contain fields for credits
        if isinstance(me_data["quota"], dict):
            remaining_credits = me_data["quota"].get("credits", None)
    # If no quota info, just proceed but it may fail quota check anyway

    if remaining_credits is not None:
        assert remaining_credits >= 5, f"Insufficient quota credits: {remaining_credits}"

    # 3. Get list of instruments to pick a valid Binance USDT trading pair symbol
    instruments_resp = session.get(BASE_URL + "/api/instruments", params={"search": "USDT"}, timeout=TIMEOUT)
    assert instruments_resp.status_code == 200, f"Failed to get instruments: {instruments_resp.text}"
    instruments_list = instruments_resp.json()
    assert isinstance(instruments_list, list) and len(instruments_list) > 0, "No instruments found"
    # Pick first instrument symbol
    symbol = instruments_list[0].get("symbol") if isinstance(instruments_list[0], dict) else None
    assert symbol, "Symbol missing in instrument"

    # 4. Prepare payload for signals generate
    payload = {
        "symbol": symbol,
        "style": "scalping",
        "riskPercent": 1.0,
        "capital": 1000.0,
        "stopLossStyle": "atr",
        "notes": "Test trade generated by automated test"
    }

    # 5. Post to signals generate endpoint
    signals_resp = session.post(BASE_URL + SIGNALS_GENERATE_ENDPOINT, json=payload, timeout=TIMEOUT)
    assert signals_resp.status_code == 200, f"Signal generation failed: {signals_resp.text}"

    result = signals_resp.json()
    # Validate that the response contains structured trade recommendation result
    # Basic validation for expected keys (typical elements expected)
    assert isinstance(result, dict), "Response is not a JSON object"
    # Check expected keys indicating a structured trade plan (names based on typical trade recommendation)
    expected_keys = ["symbol", "style", "riskPercent", "capital", "stopLossStyle", "recommendation"]
    for key in expected_keys:
        assert key in result, f"Missing key '{key}' in recommendation result"

    # recommendation expected to be a dict with trade details
    recommendation = result.get("recommendation")
    assert isinstance(recommendation, dict), "recommendation field is not an object"

    # Example keys inside recommendation advanced check
    rec_expected_keys = ["entry", "targets", "stopLoss", "tradePlan"]
    for key in rec_expected_keys:
        assert key in recommendation, f"Missing key '{key}' in recommendation details"

test_postapisignalsgeneratewithvalidinputsandquota()
